[language-server]
efm-langserver = { command = "efm-langserver" }
phpactor = { command = "phpactor" }
v-analyzer = { command = "v-analyzer", args = [""] }
neocmakelsp = { command = "neocmakelsp", args = ["--stdio"] }
pylylzer = { command = "pylyzer", args = ["--server"] }

[[language]]
name = "cmake"
auto-format = true
language-servers = [{ name = "neocmakelsp" }]


[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = [
  "py",
  "pyi",
  "py3",
  "pyw",
  "ptl",
  ".pythonstartup",
  ".pythonrc",
  "SConstruct",
  "rpy",
  "cpy",
  "ipy",
  "pyt",
  "SConscript",
]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["pylylzer"]
# TODO: pyls needs utf-8 offsets
indent = { tab-width = 4, unit = "    " }

[language.debugger]
name = "debugpy"
transport = "stdio"
command = "python"
args = ["-m",  "debugpy.adapter"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "entrypoint", completion = "filename", default = "." } ]
args = { mode = "debug", program = "{0}" }

[[language]]
name = "php"
scope = "source.php"
injection-regex = "php"
file-types = ["php", "inc", "php4", "php5", "phtml", "ctp"]
shebangs = ["php"]
roots = ["composer.json", "index.php"]
language-servers = ["phpactor"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "v"
scope = "source.v"
auto-format = true
file-types = ["v", "vv", "vsh"]
shebangs = ["v run"]
roots = ["v.mod"]
comment-token = "//"
language-servers = ["v-analyzer"]
indent = { tab-width = 4, unit = "\t" }

[[grammar]]
name = "v"
source = { git = "https://github.com/v-analyzer/v-analyzer", subpath = "tree_sitter_v", rev = "e14fdf6e661b10edccc744102e4ccf0b187aa8ad" }

[[language]]
name = "html"
scope = "text.html.basic"
injection-regex = "html"
file-types = [
  "html",
  "htm",
  "shtml",
  "xhtml",
  "xht",
  "jsp",
  "asp",
  "aspx",
  "jshtm",
  "volt",
  "rhtml",
]
language-servers = ["vscode-html-language-server"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[[language]]
name = "json"
scope = "source.json"
injection-regex = "json"
file-types = [
  "json",
  "jsonc",
  "arb",
  "ipynb",
  "geojson",
  "gltf",
  "webmanifest",
  "flake.lock",
  ".babelrc",
  ".bowerrc",
  ".jscrc",
  "js.map",
  "ts.map",
  "css.map",
  ".jslintrc",
  "jsonld",
  ".vuerc",
  "composer.lock",
  ".watchmanconfig",
  "avsc"
]
language-servers = [ "vscode-json-language-server" ]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "json"
source = { git = "https://github.com/tree-sitter/tree-sitter-json", rev = "3fef30de8aee74600f25ec2e319b62a1a870d51e" }


[[language]]
name = "gemini"
scope = "source.gmi"
file-types = ["gmi"]

[[grammar]]
name = "gemini"
source = { git = "https://github.com/blessanabraham/tree-sitter-gemini", rev = "3cc5e4bdf572d5df4277fc2e54d6299bd59a54b3" }
